### PR TITLE
Allow for large messages by concatinating until a packet with 0x1c0x0d

### PR DESCRIPTION
**Pull request by mberryman**
Pull request as requested. Allowing service to consume large HL7 Messages that span multiple TCP Packets.

### CODE REVIEW

**Comment by jsachs** [comment]
Hey @mberryman,

Sorry this one fell off our radar. If you want to rebase I'd be happy to merge.

**Comment by mberryman** [comment]
hey @jsachs,

I have rebased and fixed mere conflicts (basically removed all the code that I had replaced in my original pull request). You can complete the pull req now. Give it a test and let me know if you encounter any issues. I might

**Comment by jsachs** [comment]
@mberryman I tried restarting the build just in case, but it looks like something is going wrong with the unit tests. The first one is timing out.

**Comment by mberryman** [comment]
@jsachs,

I ran the tests and yes they're failing. Should've done that before I committed sorry. 

Looks like there is an issue with the test.js script. It is writing @ symbols to the socket instead of VT + HL7 + \r\n. The test.txt file doesn't contain the characters either. I will take a little look later.

**Comment by mberryman** [comment]
Nearly done.

  1) receives exactly the information sent

  2 passing (22ms)
  1 failing

  1) test server with client data exchange receives exactly the information sent:
     Error: done() called multiple times
      at multiple (C:\projects\node\mllp\node_modules\mocha\lib\runnable.js:175:31)
      at done (C:\projects\node\mllp\node_modules\mocha\lib\runnable.js:181:26)
      at C:\projects\node\mllp\node_modules\mocha\lib\runnable.js:199:9
      at MLLPServer.<anonymous> (C:\projects\node\mllp\test\test.js:45:13)
      at emitOne (events.js:77:13)
      at MLLPServer.emit (events.js:169:7)
      at Socket.<anonymous> (C:\projects\node\mllp\index.js:60:22)
      at emitOne (events.js:77:13)
      at Socket.emit (events.js:169:7)
      at readableAddChunk (_stream_readable.js:153:18)

CLOSED: 127.0.0.1 50506
ack received
Warning: Task "mochaTest:test" failed. Use --force to continue.

Aborted due to warnings.

**Comment by mberryman** [comment]
@jsachs 
I have sorted out the issues with the test script by sending the test server a valid HL7 MLLP Envelope. I have also added JSDOC comments. Some code editors use this for Code Completion. I think there is also a Grunt (I use Gulp, so I am unsure) Plugin/Mixin that allows you to generate html or md docs.

I will see if I can grab a large HL7 Message (I see them hourly on our network) and add it to the test scripts. It's just a matter of getting motivated enough to grab one and anonymise it, then add the test script.

**Comment by au2** [comment]
@mberryman  we are trying to cleanup our open PRs. What is the status on this? It looks like tests are passing now but PR has conflicts.  Can you resubmit with conflicts cleaned up?
1) Instead of using console.log use the new logger argument.
2) I would change 'message' to be a member of the MLLPServer in case MLLPServer is called multiple times. Not sure if that is a use case or not but just in case.

**Review by au2 — CHANGES_REQUESTED** [review]
Please see the comment.

**Comment by au2** [comment]
@mberryman looks good. I am good with moving on to node 8 but can we bump the version to 2.0.0 in case someone out there using this in other versions of node. Please update .travis.yml as well; node_js to 8 and do away with versioned install of grunt-cli. I think travis should pass then.

**Comment by mberryman** [comment]
@au2 I think that'll do it.

**Comment by au2** [comment]
looks like travis fails because capitalization of file name in the test and actual file name are not the same.  will fix after merging.

**Comment by mberryman** [comment]
@au2 Thanks mate. Yeah I see what I did there. Typo'd L (largeA08.txt), which is fine on a windows environment. Didn't fail in Windows BASH either which sucks. Trap for young players I guess (I am usually pretty careful with case switching from Windows to Linux all the time), Never mind fixed new.

**Pull request merged**
